Repository google/turbinia, pull requests merged in 2018-06, with the labels that each got.

#183 Install Plaso only for workers
  .gitignore
  MANIFEST.in
  requirements.txt
  setup.py
Labels: bug, enhancement

#190 Explicitly set project in client setup
  turbinia/state_manager.py
Labels: bug

#196 Remove bulkextractor worker/job
  turbinia/jobs/be.py
  turbinia/workers/be.py
Labels: enhancement
